image: maven:latest

stages:
  - build
  - publish

build:
  stage: build
  tags:
    - docker
  only:
    - master
    - develop
    - /^release\/v.+$
    - /^hotfix\/v.+$
    - /^feature\/.+$/
  script:
    - mvn clean compile verify
  artifacts:
    paths:
      - "target/*.jar"
    expire_in: 1h

publish:
  stage: publish
  image: docker:stable
  services:
    - docker:dind
  tags:
    - docker
  variables:
    DOCKER_TAG: "latest"
  before_script:
    - docker login -u $temp_username -p $temp_password
  script: docker push entelectchallenge2020/game-runner-qa
  only:
    - master



